name: Exercice6
version: 0.0.1
author: Charaf-eddine Metiaf
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
homepage: index.html
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  dartlero: any
  route_hierarchical: '>=0.5.0 <0.7.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- script_inliner
